# Generated by Django 3.1.6 on 2021-02-10 12:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseapp', '0002_userlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlist',
            name='role',
            field=models.CharField(choices=[('Company', 'Company'), ('MainBranch', 'MainBranch'), ('CustomBranch', 'CustomBranch')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
