# Generated by Django 3.1.6 on 2021-02-10 12:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseapp', '0003_userlist_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlist',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
