# Generated by Django 3.1.6 on 2021-02-14 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseapp', '0010_auto_20210214_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlist',
            name='role',
        ),
        migrations.RemoveField(
            model_name='userlist',
            name='user',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='UserList',
        ),
    ]
