# Generated by Django 3.1.6 on 2021-02-14 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseapp', '0011_auto_20210214_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='issue_to',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
