# Generated by Django 3.1.6 on 2021-02-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseapp', '0012_product_issue_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='issue_to',
            field=models.CharField(blank=True, default='0', max_length=50, null=True),
        ),
    ]
